name: cibuildwheel build

on:
  workflow_dispatch:
  push:
    branches:
      - cibuildwheel

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022, macOS-11]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Use cmake
        run: cmake --version

      - name: Use cmake
        if: matrix.cibw_archs == 'win32'
        run: cmake -A Win32

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.15.0

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse
        # to supply options, put them in 'env', like:
        env:
          MACOSX_DEPLOYMENT_TARGET: 10.15
          CIBW_ARCHS_MACOS: "x86_64 universal2 arm64"

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl